### Set path
path+=("$HOME/bin")
export PATH

# Set the default editor to use.  This'll use the best of whatever is available.
if hash nvim 2>/dev/null; then
    export EDITOR="nvim"
elif hash vim 2>/dev/null; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

# Set some zsh options
#setopt CORRECT              #Spellcheck commands
setopt AUTO_CD              #Automatically cd if entry = dir name
#setopt RM_STAR_WAIT         #Make us wait 10 seconds before deleting
#setopt VI                   #Use vi-like entry
#setopt CSHJUNKIEQUOTES      #Don't let us enter if quotes are not completed
setopt NO_BEEP              #Shut up, computer
setopt NO_FLOW_CONTROL      #Disables ctrl-s (stupid nonsense that "pauses" screen)
setopt EXTENDED_GLOB        #Make glob better
setopt HISTIGNOREDUPS       #Don't save next line if it is the same as prev
#setopt HIST_IGNORE_ALL_DUPS #Don't save ANY repeated commands
setopt HIST_REDUCE_BLANKS   #Pretty    obvious,    right?
setopt SHARE_HISTORY        #Share history between shells
setopt APPEND_HISTORY       #Don't overwrite
setopt EXTENDED_HISTORY     #Save when and how long a command was run
setopt COMPLETEALIASES      #Tab complete aliases

# Some handy aliases
alias e='$EDITOR'
alias cpv='rsync -poghb --backup-dir=/tmp/rsync -e /dev/null --progress --'
alias pa="source venv/bin/activate"

# So we can use normal bash shortcuts instead of vim
bindkey -e

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

bindkey -M vicmd "q" push-line

# Ensure that arrow keys work as they should
bindkey '\e[A' up-line-or-history
bindkey '\e[B' down-line-or-history

bindkey '\eOA' up-line-or-history
bindkey '\eOB' down-line-or-history

bindkey '\e[C' forward-char
bindkey '\e[D' backward-char

bindkey '\eOC' forward-char
bindkey '\eOD' backward-char

bindkey -M viins 'jj' vi-cmd-mode
bindkey -M vicmd 'u' undo

# Rebind the insert key.  I really can't stand what it currently does.
bindkey '\e[2~' overwrite-mode

# Rebind the delete key. Again, useless.
bindkey '\e[3~' delete-char

bindkey -M vicmd '!' edit-command-output

# it's like, space AND completion.
bindkey -M viins ' ' magic-space

# Activate oh my zsh if it's available
export ZSH=$HOME/.oh-my-zsh
if [ -f $ZSH/oh-my-zsh.sh ]; then
    # Custom path for custom stuff (like our theme)
    ZSH_CUSTOM="$HOME/.dotfiles/shell/"

    # The theme we'll use
    ZSH_THEME="nyx"

    # Display red dots whilst waiting for completion.
    COMPLETION_WAITING_DOTS="true"

    # Plugins to use
    plugins=(git nmap pyenv tmux)

    source $ZSH/oh-my-zsh.sh
fi

# Disable x11's ugly passphrase prompt
unset SSH_ASKPASS
