# Make sure path includes our local bin directory
path+=("$HOME/bin")

# Set the default editor to use.  This'll use the best of whatever is available.
if hash vim 2>/dev/null; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

# Spellcheck commands
#setopt CORRECT

# Automatically cd if entry = dir name
setopt AUTO_CD

# Make us wait 10 seconds before deleting
#setopt RM_STAR_WAIT

# Use vi-like entry
#setopt VI

# Don't let us enter if quotes are not completed
#setopt CSHJUNKIEQUOTES

# Shut up, computer
setopt NO_BEEP

# Disables ctrl-s (stupid nonsense that "pauses" screen)
setopt NO_FLOW_CONTROL

# Make glob better
setopt EXTENDED_GLOB

# Don't save next line if it is the same as prev
setopt HISTIGNOREDUPS

#setopt HIST_IGNORE_ALL_DUPS #Don't save ANY repeated commands
# Pretty    obvious,    right?
setopt HIST_REDUCE_BLANKS

# Share history between shells
setopt SHARE_HISTORY

# Don't overwrite
setopt APPEND_HISTORY

# Save when and how long a command was run
setopt EXTENDED_HISTORY

# Tab complete aliases
setopt COMPLETEALIASES

# Some handy aliases
alias e="$EDITOR"
alias emacs="emacs -nw"
alias cpv="rsync -poghb --backup-dir=/tmp/rsync -e /dev/null --progress --"
alias pa="source venv/bin/activate"

# If we have nvim installed (we should), use it over vim seamlessly
if type "nvim" > /dev/null; then
    alias vim="nvim"
fi

# So we can use normal bash shortcuts instead of vim
bindkey -e

# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

bindkey -M vicmd "q" push-line

# Ensure that arrow keys work as they should
bindkey '\e[A' up-line-or-history
bindkey '\e[B' down-line-or-history

bindkey '\eOA' up-line-or-history
bindkey '\eOB' down-line-or-history

bindkey '\e[C' forward-char
bindkey '\e[D' backward-char

bindkey '\eOC' forward-char
bindkey '\eOD' backward-char

bindkey -M viins 'jj' vi-cmd-mode
bindkey -M vicmd 'u' undo

# Rebind the insert key.  I really can't stand what it currently does.
bindkey '\e[2~' overwrite-mode

# Rebind the delete key. Again, useless.
bindkey '\e[3~' delete-char

bindkey -M vicmd '!' edit-command-output

# it's like, space AND completion.
bindkey -M viins ' ' magic-space

# Activate oh my zsh if it's available
export ZSH=$HOME/.oh-my-zsh
if [ -f $ZSH/oh-my-zsh.sh ]; then
    # Custom path for custom stuff (like our theme)
    #ZSH_CUSTOM="$HOME/.dotfiles/config/shell/"

    # The theme we'll use
    ZSH_THEME="nyx"

    # Display red dots whilst waiting for completion.
    COMPLETION_WAITING_DOTS="true"

    # Plugins to use
    plugins=(git nmap pyenv tmux zsh-autosuggestions zsh-completions zsh-syntax-highlighting)

    source $ZSH/oh-my-zsh.sh
fi

# If I'm at Google, use some stuff to work with internal systems.
if [ -f $HOME/.zshrc.google ]; then
    source $HOME/.zshrc.google
fi

# Disable x11's ugly passphrase prompt
unset SSH_ASKPASS
