#!/bin/sh

# Add custom fonts given in dotfiles
xset +fp ~/.dotfiles/resources/fonts/terminus
xset fp rehash
xset -dpms

# Load Xresources
xrdb -load ~/.Xresources

# Run compositor
compton --conf ~/.config/compton/compton.conf &

# Run ssh agent
eval `ssh-agent`

# Run yabar
#yabar &

# Add background
feh --bg-tile ~/.dotfiles/resources/img/bg2.jpg

# Launch bspwm
sxhkd &
exec bspwm
